### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by cardangi** [jota-br/php-responsive-simple#2]
Adicionar bootstrap ajudaria bastante no projeto, deixando mais dinâmico e bonito, sem necessidade de fazer tanto CSS Manual.

E também não vejo tanta necessidade de usar tanto PHP se é só um blog simples, invista mais no HTML E CSS para ficar dinâmico e bonito. PHP é apenas funcionalidades. Não tem se quer um arquivo .html/.xhtml

**Comment by jota-br** [comment]
Obrigado pelas dicas, depois tento botar em prática. Na realidade não pretendo botar em uso esse site, o objetivo do código é esse, um blog simples, mas estou fazendo apenas para aprender a usar o php, html, etc. De qualquer forma agradeço muito seu insight.
